### PR TITLE
tos-640-modal-without-availability

### PR DESCRIPTION
**Pull request by basselalsayed**
*  wrap all launchToshi logic in promise since modal init is async
* convert arrows to named functions (in case of hoisting issues)

### CODE REVIEW

**Comment by edwinwills** [comment]
Can you split this into 2 PRs, one that does the linting, and one that does the functional change? Finding it hard to see what is a code change, and what is a lint change. Thanks!

**Comment by basselalsayed** [comment]
@edwinwills check this [commit](https://github.com/toshitech/toshi-magento-plugin/pull/6/commits/ecc28c5cd0d0960a7af8d01e3e22b609bc317d40)

**Review by edwinwills — APPROVED** [review]
Nice

**Comment by edwinwills** [comment]
Only downside with changes to this plugin, is that we need brands to update it manually their side before the change will come into effect. Just checking that the old version of the plugin, and this one, will work side by side?

**Review by chris-john-hopkins — APPROVED** [review]

**Comment by basselalsayed** [comment]
Closed as we worked around by having async and sync modal init options

**Pull request closed without merging**
